package com.Wsdl2Code.WebServices.EnterpriseAPISoapService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 7/4/2014 4:34:19 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class autoPay implements KvmSerializable {

    public String amountInCents;
    public String autoPayBeneficiaryRef;
    public String autoPayCardNumber;
    public String autoPayErrorCode;
    public String autoPayNotificationHashedSignature;
    public String autoPayPaymentDate;
    public String autoPayPaymentrecordId;
    public String autoPayRandomSeed;
    public String autoPayReference;
    public String autoPayStatus;
    public String autoPayTotalAmount;
    public String autoPayTransactionId;
    public String defaultPM;
    public String pmId;

    public autoPay() {
    }

    public autoPay(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("amountInCents")) {
            Object obj = soapObject.getProperty("amountInCents");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                amountInCents = j.toString();
            } else if (obj != null && obj instanceof String) {
                amountInCents = (String) obj;
            }
        }
        if (soapObject.hasProperty("autoPayBeneficiaryRef")) {
            Object obj = soapObject.getProperty("autoPayBeneficiaryRef");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                autoPayBeneficiaryRef = j.toString();
            } else if (obj != null && obj instanceof String) {
                autoPayBeneficiaryRef = (String) obj;
            }
        }
        if (soapObject.hasProperty("autoPayCardNumber")) {
            Object obj = soapObject.getProperty("autoPayCardNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                autoPayCardNumber = j.toString();
            } else if (obj != null && obj instanceof String) {
                autoPayCardNumber = (String) obj;
            }
        }
        if (soapObject.hasProperty("autoPayErrorCode")) {
            Object obj = soapObject.getProperty("autoPayErrorCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                autoPayErrorCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                autoPayErrorCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("autoPayNotificationHashedSignature")) {
            Object obj = soapObject.getProperty("autoPayNotificationHashedSignature");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                autoPayNotificationHashedSignature = j.toString();
            } else if (obj != null && obj instanceof String) {
                autoPayNotificationHashedSignature = (String) obj;
            }
        }
        if (soapObject.hasProperty("autoPayPaymentDate")) {
            Object obj = soapObject.getProperty("autoPayPaymentDate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                autoPayPaymentDate = j.toString();
            } else if (obj != null && obj instanceof String) {
                autoPayPaymentDate = (String) obj;
            }
        }
        if (soapObject.hasProperty("autoPayPaymentrecordId")) {
            Object obj = soapObject.getProperty("autoPayPaymentrecordId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                autoPayPaymentrecordId = j.toString();
            } else if (obj != null && obj instanceof String) {
                autoPayPaymentrecordId = (String) obj;
            }
        }
        if (soapObject.hasProperty("autoPayRandomSeed")) {
            Object obj = soapObject.getProperty("autoPayRandomSeed");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                autoPayRandomSeed = j.toString();
            } else if (obj != null && obj instanceof String) {
                autoPayRandomSeed = (String) obj;
            }
        }
        if (soapObject.hasProperty("autoPayReference")) {
            Object obj = soapObject.getProperty("autoPayReference");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                autoPayReference = j.toString();
            } else if (obj != null && obj instanceof String) {
                autoPayReference = (String) obj;
            }
        }
        if (soapObject.hasProperty("autoPayStatus")) {
            Object obj = soapObject.getProperty("autoPayStatus");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                autoPayStatus = j.toString();
            } else if (obj != null && obj instanceof String) {
                autoPayStatus = (String) obj;
            }
        }
        if (soapObject.hasProperty("autoPayTotalAmount")) {
            Object obj = soapObject.getProperty("autoPayTotalAmount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                autoPayTotalAmount = j.toString();
            } else if (obj != null && obj instanceof String) {
                autoPayTotalAmount = (String) obj;
            }
        }
        if (soapObject.hasProperty("autoPayTransactionId")) {
            Object obj = soapObject.getProperty("autoPayTransactionId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                autoPayTransactionId = j.toString();
            } else if (obj != null && obj instanceof String) {
                autoPayTransactionId = (String) obj;
            }
        }
        if (soapObject.hasProperty("defaultPM")) {
            Object obj = soapObject.getProperty("defaultPM");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                defaultPM = j.toString();
            } else if (obj != null && obj instanceof String) {
                defaultPM = (String) obj;
            }
        }
        if (soapObject.hasProperty("pmId")) {
            Object obj = soapObject.getProperty("pmId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                pmId = j.toString();
            } else if (obj != null && obj instanceof String) {
                pmId = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return amountInCents;
            case 1:
                return autoPayBeneficiaryRef;
            case 2:
                return autoPayCardNumber;
            case 3:
                return autoPayErrorCode;
            case 4:
                return autoPayNotificationHashedSignature;
            case 5:
                return autoPayPaymentDate;
            case 6:
                return autoPayPaymentrecordId;
            case 7:
                return autoPayRandomSeed;
            case 8:
                return autoPayReference;
            case 9:
                return autoPayStatus;
            case 10:
                return autoPayTotalAmount;
            case 11:
                return autoPayTransactionId;
            case 12:
                return defaultPM;
            case 13:
                return pmId;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 14;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "amountInCents";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "autoPayBeneficiaryRef";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "autoPayCardNumber";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "autoPayErrorCode";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "autoPayNotificationHashedSignature";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "autoPayPaymentDate";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "autoPayPaymentrecordId";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "autoPayRandomSeed";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "autoPayReference";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "autoPayStatus";
                break;
            case 10:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "autoPayTotalAmount";
                break;
            case 11:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "autoPayTransactionId";
                break;
            case 12:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "defaultPM";
                break;
            case 13:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "pmId";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
