package com.Wsdl2Code.WebServices.EnterpriseAPISoapService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 7/4/2014 4:34:19 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class balance implements KvmSerializable {

    public String amount;
    public String label;
    public String type;

    public balance() {
    }

    public balance(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("amount")) {
            Object obj = soapObject.getProperty("amount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                amount = j.toString();
            } else if (obj != null && obj instanceof String) {
                amount = (String) obj;
            }
        }
        if (soapObject.hasProperty("label")) {
            Object obj = soapObject.getProperty("label");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                label = j.toString();
            } else if (obj != null && obj instanceof String) {
                label = (String) obj;
            }
        }
        if (soapObject.hasProperty("type")) {
            Object obj = soapObject.getProperty("type");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                type = j.toString();
            } else if (obj != null && obj instanceof String) {
                type = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return amount;
            case 1:
                return label;
            case 2:
                return type;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "amount";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "label";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "type";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
