package com.Wsdl2Code.WebServices.EnterpriseAPISoapService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 7/4/2014 4:34:19 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class ebucks implements KvmSerializable {

    public String amountInCents;
    public String ebucksErrorCode;
    public String ebucksMerchantId;
    public String ebucksMerchantReference;
    public String ebucksReference;
    public String ebucksToken;
    public String ebucksValidity;
    public String ebucksValueGranted;
    public String defaultPM;
    public String pmId;

    public ebucks() {
    }

    public ebucks(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("amountInCents")) {
            Object obj = soapObject.getProperty("amountInCents");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                amountInCents = j.toString();
            } else if (obj != null && obj instanceof String) {
                amountInCents = (String) obj;
            }
        }
        if (soapObject.hasProperty("ebucksErrorCode")) {
            Object obj = soapObject.getProperty("ebucksErrorCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                ebucksErrorCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                ebucksErrorCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("ebucksMerchantId")) {
            Object obj = soapObject.getProperty("ebucksMerchantId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                ebucksMerchantId = j.toString();
            } else if (obj != null && obj instanceof String) {
                ebucksMerchantId = (String) obj;
            }
        }
        if (soapObject.hasProperty("ebucksMerchantReference")) {
            Object obj = soapObject.getProperty("ebucksMerchantReference");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                ebucksMerchantReference = j.toString();
            } else if (obj != null && obj instanceof String) {
                ebucksMerchantReference = (String) obj;
            }
        }
        if (soapObject.hasProperty("ebucksReference")) {
            Object obj = soapObject.getProperty("ebucksReference");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                ebucksReference = j.toString();
            } else if (obj != null && obj instanceof String) {
                ebucksReference = (String) obj;
            }
        }
        if (soapObject.hasProperty("ebucksToken")) {
            Object obj = soapObject.getProperty("ebucksToken");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                ebucksToken = j.toString();
            } else if (obj != null && obj instanceof String) {
                ebucksToken = (String) obj;
            }
        }
        if (soapObject.hasProperty("ebucksValidity")) {
            Object obj = soapObject.getProperty("ebucksValidity");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                ebucksValidity = j.toString();
            } else if (obj != null && obj instanceof String) {
                ebucksValidity = (String) obj;
            }
        }
        if (soapObject.hasProperty("ebucksValueGranted")) {
            Object obj = soapObject.getProperty("ebucksValueGranted");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                ebucksValueGranted = j.toString();
            } else if (obj != null && obj instanceof String) {
                ebucksValueGranted = (String) obj;
            }
        }
        if (soapObject.hasProperty("defaultPM")) {
            Object obj = soapObject.getProperty("defaultPM");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                defaultPM = j.toString();
            } else if (obj != null && obj instanceof String) {
                defaultPM = (String) obj;
            }
        }
        if (soapObject.hasProperty("pmId")) {
            Object obj = soapObject.getProperty("pmId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                pmId = j.toString();
            } else if (obj != null && obj instanceof String) {
                pmId = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return amountInCents;
            case 1:
                return ebucksErrorCode;
            case 2:
                return ebucksMerchantId;
            case 3:
                return ebucksMerchantReference;
            case 4:
                return ebucksReference;
            case 5:
                return ebucksToken;
            case 6:
                return ebucksValidity;
            case 7:
                return ebucksValueGranted;
            case 8:
                return defaultPM;
            case 9:
                return pmId;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 10;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "amountInCents";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ebucksErrorCode";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ebucksMerchantId";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ebucksMerchantReference";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ebucksReference";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ebucksToken";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ebucksValidity";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ebucksValueGranted";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "defaultPM";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "pmId";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
