package com.Wsdl2Code.WebServices.EnterpriseAPISoapService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 7/4/2014 4:34:19 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

public interface IWsdl2CodeEvents {
    public void Wsdl2CodeStartedRequest();

    public void Wsdl2CodeFinished(String methodName, Object Data);

    public void Wsdl2CodeFinishedWithException(Exception ex);

    public void Wsdl2CodeEndedRequest();
}
