package com.Wsdl2Code.WebServices.EnterpriseAPISoapService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 7/4/2014 4:34:19 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class recurringDetails implements KvmSerializable {

    public String deductionDay;
    public String frequency;
    public String recurrences;
    public String recurringPaymentToken;
    public String statementDescription;

    public recurringDetails() {
    }

    public recurringDetails(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("deductionDay")) {
            Object obj = soapObject.getProperty("deductionDay");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                deductionDay = j.toString();
            } else if (obj != null && obj instanceof String) {
                deductionDay = (String) obj;
            }
        }
        if (soapObject.hasProperty("frequency")) {
            Object obj = soapObject.getProperty("frequency");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                frequency = j.toString();
            } else if (obj != null && obj instanceof String) {
                frequency = (String) obj;
            }
        }
        if (soapObject.hasProperty("recurrences")) {
            Object obj = soapObject.getProperty("recurrences");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                recurrences = j.toString();
            } else if (obj != null && obj instanceof String) {
                recurrences = (String) obj;
            }
        }
        if (soapObject.hasProperty("recurringPaymentToken")) {
            Object obj = soapObject.getProperty("recurringPaymentToken");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                recurringPaymentToken = j.toString();
            } else if (obj != null && obj instanceof String) {
                recurringPaymentToken = (String) obj;
            }
        }
        if (soapObject.hasProperty("statementDescription")) {
            Object obj = soapObject.getProperty("statementDescription");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                statementDescription = j.toString();
            } else if (obj != null && obj instanceof String) {
                statementDescription = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return deductionDay;
            case 1:
                return frequency;
            case 2:
                return recurrences;
            case 3:
                return recurringPaymentToken;
            case 4:
                return statementDescription;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "deductionDay";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "frequency";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "recurrences";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "recurringPaymentToken";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "statementDescription";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
