package com.Wsdl2Code.WebServices.EnterpriseAPISoapService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 7/4/2014 4:34:19 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class secure3D implements KvmSerializable {

    public String secure3DId;
    public String secure3DUrl;

    public secure3D() {
    }

    public secure3D(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("secure3DId")) {
            Object obj = soapObject.getProperty("secure3DId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                secure3DId = j.toString();
            } else if (obj != null && obj instanceof String) {
                secure3DId = (String) obj;
            }
        }
        if (soapObject.hasProperty("secure3DUrl")) {
            Object obj = soapObject.getProperty("secure3DUrl");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                secure3DUrl = j.toString();
            } else if (obj != null && obj instanceof String) {
                secure3DUrl = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return secure3DId;
            case 1:
                return secure3DUrl;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "secure3DId";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "secure3DUrl";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
